// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schedule.io.Infra.Data.SqlServerDB;

namespace Schedule.io.Infra.Data.SqlServerDB.Migrations
{
    [DbContext(typeof(AgendaContext))]
    [Migration("20200409205516_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Schedule.io.Core.Core.Data.EventSourcing.StoredEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AggregatedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoredEvents");
                });

            modelBuilder.Entity("Schedule.io.Core.Models.Agenda", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AtualizadoAs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoAs")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("bit");

                    b.Property<bool>("Publico")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("Schedule.io.Core.Models.AgendaUsuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgendaId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("AtualizadoAs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoAs")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Inativo")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AgendaUsuario");
                });

            modelBuilder.Entity("Schedule.io.Core.Models.Convite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AtualizadoAs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoAs")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailConvidado")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EventoAgendaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventoId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventoAgendaId");

                    b.ToTable("Convite");
                });

            modelBuilder.Entity("Schedule.io.Core.Models.EventoAgenda", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgendaId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("AtualizadoAs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoAs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataLimiteConfirmacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnName("EventoAgenda_Descricao")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Frequencia")
                        .HasColumnType("int");

                    b.Property<string>("IdentificadorExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("bit");

                    b.Property<string>("LocalId")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("OcupaUsuario")
                        .HasColumnType("bit");

                    b.Property<bool>("Publico")
                        .HasColumnType("bit");

                    b.Property<int>("QuantidadeMinimaDeUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EventoAgenda");
                });

            modelBuilder.Entity("Schedule.io.Core.Models.Local", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AtualizadoAs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoAs")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IdentificadorExterno")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("bit");

                    b.Property<int>("LotacaoMaxima")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Reserva")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Local");
                });

            modelBuilder.Entity("Schedule.io.Core.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AtualizadoAs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoAs")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Inativo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Schedule.io.Core.Models.AgendaUsuario", b =>
                {
                    b.OwnsOne("Schedule.io.Core.Models.PermissoesAgenda", "Permissoes", b1 =>
                        {
                            b1.Property<string>("AgendaUsuarioId")
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("AgendaUsuarioId");

                            b1.ToTable("AgendaUsuario");

                            b1.WithOwner()
                                .HasForeignKey("AgendaUsuarioId");
                        });
                });

            modelBuilder.Entity("Schedule.io.Core.Models.Convite", b =>
                {
                    b.HasOne("Schedule.io.Core.Models.EventoAgenda", null)
                        .WithMany("Convites")
                        .HasForeignKey("EventoAgendaId");

                    b.OwnsOne("Schedule.io.Core.Models.PermissoesConvite", "Permissoes", b1 =>
                        {
                            b1.Property<string>("ConviteId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("ConvidaUsuario")
                                .HasColumnName("ConvidaUsuario")
                                .HasColumnType("bit");

                            b1.Property<bool>("ModificaEvento")
                                .HasColumnName("ModificaEvento")
                                .HasColumnType("bit");

                            b1.Property<bool>("VeListaDeConvidados")
                                .HasColumnName("VeListaDeConvidados")
                                .HasColumnType("bit");

                            b1.HasKey("ConviteId");

                            b1.ToTable("Convite");

                            b1.WithOwner()
                                .HasForeignKey("ConviteId");
                        });
                });

            modelBuilder.Entity("Schedule.io.Core.Models.EventoAgenda", b =>
                {
                    b.OwnsOne("Schedule.io.Core.Models.TipoEvento", "Tipo", b1 =>
                        {
                            b1.Property<string>("EventoAgendaId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("AtualizadoAs")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("CriadoAs")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Descricao")
                                .HasColumnName("Descricao")
                                .HasColumnType("varchar(500)");

                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Inativo")
                                .HasColumnType("bit");

                            b1.Property<string>("Nome")
                                .HasColumnName("Nome")
                                .HasColumnType("varchar(120)");

                            b1.HasKey("EventoAgendaId");

                            b1.ToTable("EventoAgenda");

                            b1.WithOwner()
                                .HasForeignKey("EventoAgendaId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
